### ISSUE TITLE
Example does not work on windows 11

### ISSUE THREAD

**Issue by mmasdivins** [alexmercerind/flutter_native_view#23]
Hello, 
I was trying to run the example on windows 11, the app opens but it shows a blank space where the VLC embedded app should show:
![imatge](https://user-images.githubusercontent.com/63245359/200515816-7ffff997-cd40-49ae-b601-683c3d381ad7.png)

**Comment by mmasdivins** [comment]
After trying with notepad:

```
    NativeViewController(
      handle: FindWindow(
        'Notepad'.toNativeUtf16(),
        nullptr,
      ),
      hitTestBehavior: HitTestBehavior.translucent,
    ),
```
It shows the app, but is really laggy and has weird behaviour:
![imatge](https://user-images.githubusercontent.com/63245359/200529671-247e58e7-594b-4967-b133-18e06b620e4e.png)

I tried to capture a video, but for some reason the NativeView widgets is all black on the recording.

Also I will like to know if there is a way to embed and app without opening beforehand?

**Comment by nelchael730** [comment]
Why was this closed? still doesn't work
