### ISSUE TITLE
Flutter 3.0 compatibility issue

### ISSUE THREAD

**Issue by kion** [alexmercerind/flutter_native_view#9]
Looks like there's a compatibility issue with Flutter 3.0.

I get the following error while trying to build a previously working (and built using Flutter 2.x) app:

`flutter_native_view-0.0.1+1/lib/src/widgets.dart:87:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.`

This seems to be a known Flutter 3.0 upgrade issue (which would require some code migration changes) explained in the Flutter 3.0 release notes here:

https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0

**Comment by kion** [comment]
Oh. The error message was actually (confusingly enough) prefixed with `ERROR:`, but I now see that it wasn't the actual cause of the issue I experience (it's related to something else). Thanks for taking a look!

**Comment by fzyzcjy** [comment]
+1 Just remove that "!"

**Comment by alexmercerind** [comment]
Addressed. Along with few other issues & minor API change. Released: v0.0.2.

Also, project is now under MIT licensing.
